# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZjNlZWIxM2IwODE4YWZjNjU4NDIwMjVlMDBlNmZjNDNlZDRmY2E3Y2VlNDYwZmU3YTY0OGM2NzVhYTJhMjVjNGU5NjUzMzFlNzc5YjFkM2RlMWQ0MTY4YjhjNjcyMWUzNjhhM2NmYjJjNzA4YTE2ZDYzNzViMmViZjM5ZTNlNGQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
